"""removed ref_rel, added reference.category_id, added ref_order

Revision ID: 10_rem_ref_rel_add_ref_order
Revises: 9_dojo_nullable
Create Date: 2020-12-12 20:11:11.948513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10_rem_ref_rel_add_ref_order'
down_revision = '9_dojo_nullable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ref_rel')
    op.add_column('reference', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('ref_cat_ibfk', 'reference', 'ref_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ref_cat_ibfk', 'reference', type_='foreignkey')
    op.drop_column('reference', 'category_id')
    op.create_table('ref_rel',
    sa.Column('ref_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ref_category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ref_category_id'], ['ref_category.id'], name='ref_rel_ibfk_1'),
    sa.ForeignKeyConstraint(['ref_id'], ['reference.id'], name='ref_rel_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('ref_order')
    # ### end Alembic commands ###
