"""create ss country, state - add table data after

Revision ID: 1_create_country_state
Revises: 19f87c2a8cd2
Create Date: 2020-04-23 00:31:33.174673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1_create_country_state'
down_revision = '19f87c2a8cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
        sa.Column('ISO_number', sa.Integer(), nullable=False),
        sa.Column('ISO', sa.String(length=2), nullable=False),
        sa.Column('ISO3', sa.String(length=3), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('phone_code', sa.String(length=50), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('ISO_number')
    )

    op.create_table('state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('country_ISO_number', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('ISO', sa.String(length=3), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state')
    op.drop_table('country')
    # ### end Alembic commands ###
