"""training table added

Revision ID: 23504c949e40
Revises: 19f87c2a8cd2
Create Date: 2020-04-23 00:31:33.174673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23504c949e40'
down_revision = '19f87c2a8cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training')
    # ### end Alembic commands ###
