"""create style, org, dojo, person - add data after

Revision ID: 2_create_style_org_dojo_person
Revises: 1_create_country_state
Create Date: 2020-04-23 00:45:04.751337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2_create_style_org_dojo_person'
down_revision = '1_create_country_state'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('style',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(25), nullable=False),
        sa.Column('kanji', sa.String(25), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('founder_person_id', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table('org',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('acronym', sa.String(25), nullable=True),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('japaneseName', sa.String(50), nullable=True),
        sa.Column('kanji', sa.String(25), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('style_id', sa.Integer(), nullable=True),
        sa.Column('founder_person_id', sa.Integer(), nullable=True),
        sa.Column('headInstructor_person_id', sa.Integer(), nullable=True),
        sa.Column('president_person_id', sa.Integer(), nullable=True),
        sa.Column('honbu_dojo_id', sa.Integer(), nullable=True),
        sa.Column('logo', sa.String(100), nullable=True),
        sa.Column('created_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table('dojo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=True),
        sa.Column('headInstructor_person_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(50), nullable=True),
        sa.Column('street', sa.String(50), nullable=True),
        sa.Column('city', sa.String(50), nullable=True),
        sa.Column('zip', sa.String(50), nullable=True),
        sa.Column('state_id', sa.Integer(), nullable=True),
        sa.Column('siteURL', sa.String(50), nullable=True),
        sa.Column('email', sa.String(50), nullable=True),
        sa.Column('phone', sa.Integer(), nullable=True),
        sa.Column('fax', sa.Integer(), nullable=True),
        sa.Column('mapURL', sa.Text(), nullable=True),
        sa.Column('isCountryHQ', sa.Integer(), nullable=True),
        sa.Column('created_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table('person',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('firstName', sa.String(25), nullable=True),
        sa.Column('lastName', sa.String(25), nullable=False),
        sa.Column('altLastName', sa.String(25), nullable=True),
        sa.Column('DoB', sa.Date(), nullable=True),
        sa.Column('DoD', sa.Date(), nullable=True),
        sa.Column('style_id', sa.Integer(), nullable=True),
        sa.Column('org_id', sa.Integer(), nullable=True),
        sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('pic', sa.String(25), nullable=True),
        sa.Column('bio', sa.Text(), nullable=True),
        sa.Column('created_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org')
    op.drop_table('style')
    op.drop_table('dojo')
    op.drop_table('person')

    # ### end Alembic commands ###
