"""deleted Chronology

Revision ID: 30daa80c1018
Revises: 23504c949e40
Create Date: 2020-04-23 00:45:04.751337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30daa80c1018'
down_revision = '23504c949e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chronology')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronology',
    sa.Column('id', mysql.INTEGER(display_width=6), autoincrement=True, nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('media', mysql.VARCHAR(length=125), nullable=True),
    sa.Column('media_credit', mysql.VARCHAR(length=125), nullable=True),
    sa.Column('media_caption', mysql.TEXT(), nullable=True),
    sa.Column('created_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
