"""style-org rel

Revision ID: 39b354802da1
Revises: 30daa80c1018
Create Date: 2020-04-23 01:39:05.648920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b354802da1'
down_revision = '30daa80c1018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'org', 'style', ['style_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org', type_='foreignkey')
    # ### end Alembic commands ###
