"""rels 2

Revision ID: 3ce7b668f066
Revises: ccdade22c9b1
Create Date: 2020-04-23 02:04:44.224682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce7b668f066'
down_revision = 'ccdade22c9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'state', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='foreignkey')
    # ### end Alembic commands ###
