"""add ss unique, rels

Revision ID: 4_add_ss_relationships
Revises: 3_create_glossary_ref_video_pub
Create Date: 2020-04-23 01:51:21.272121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4_add_ss_relationships'
down_revision = '3_create_glossary_ref_video_pub'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(op.f('country_ISO_number_uindex'), 'country', ['ISO_number'], unique=True)
    op.create_index(op.f('country_ISO_uindex'), 'country', ['ISO'], unique=True)
    op.create_index(op.f('country_ISO3_uindex'), 'country', ['ISO3'], unique=True)
    op.create_unique_constraint('country_name_uindex', 'country', ['name'])

    op.create_unique_constraint('state_id_uindex', 'state', ['id'])
    op.create_foreign_key('state_country_ISO_number_fk', 'state', 'country', ['country_ISO_number'], ['ISO_number'])

    op.create_index(op.f('style_name_uindex'), 'style', ['name'], unique=True)
    op.create_index(op.f('style_kanji_uindex'), 'style', ['kanji'], unique=True)

    op.create_foreign_key('org_style_fk', 'org', 'style', ['style_id'], ['id'])

    op.create_unique_constraint('dojo_email_uindex', 'dojo', ['email'])
    op.create_unique_constraint('dojo_siteURL_uindex', 'dojo', ['siteURL'])
    op.create_unique_constraint('dojo_phone_uindex', 'dojo', ['phone'])
    op.create_unique_constraint('dojo_fax_uindex', 'dojo', ['fax'])
    op.create_foreign_key('dojo_org_fk', 'dojo', 'org', ['org_id'], ['id'])
    op.create_foreign_key('dojo_state_fk', 'dojo', 'state', ['state_id'], ['id'])
    op.create_foreign_key('dojo_person_headInstructor_fk', 'dojo', 'person', ['headInstructor_person_id'], ['id'])

    op.create_foreign_key('person_org_fk', 'person', 'org', ['org_id'], ['id'])
    op.create_foreign_key('person_style_fk', 'person', 'style', ['style_id'], ['id'])

    op.create_foreign_key('tech_glossary_fk', 'reference', 'glossary', ['glossary_id'], ['id'])
    op.create_foreign_key('tech_person_fk', 'reference', 'person', ['person_id'], ['id'])
    op.create_foreign_key('tech_video_fk', 'reference', 'video', ['video_id'], ['id'])
    op.create_foreign_key('tech_publication_fk', 'reference', 'publication', ['pub_id'], ['id'])

    op.create_unique_constraint('video_URL_uindex', 'video', ['URL'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_URL_uindex', 'video', type_='unique')

    op.drop_constraint('tech_publication_fk', 'reference', type_='foreignkey')
    op.drop_constraint('tech_video_fk', 'reference', type_='foreignkey')
    op.drop_constraint('tech_person_fk', 'reference', type_='foreignkey')
    op.drop_constraint('tech_glossary_fk', 'reference', type_='foreignkey')

    op.drop_constraint('person_style_fk', 'person', type_='foreignkey')
    op.drop_constraint('person_org_fk', 'person', type_='foreignkey')

    op.drop_constraint('dojo_person_headInstructor_fk', 'dojo', type_='foreignkey')
    op.drop_constraint('dojo_state_fk', 'dojo', type_='foreignkey')
    op.drop_constraint('dojo_org_fk', 'dojo', type_='foreignkey')
    op.drop_constraint('dojo_fax_uindex', 'dojo', type_='unique')
    op.drop_constraint('dojo_phone_uindex', 'dojo', type_='unique')
    op.drop_constraint('dojo_siteURL_uindex', 'dojo', type_='unique')
    op.drop_constraint('dojo_email_uindex', 'dojo', type_='unique')

    op.drop_constraint('org_style_fk', 'org', type_='foreignkey')

    op.drop_index(op.f('style_kanji_uindex'), table_name='style')
    op.drop_index(op.f('style_name_uindex'), table_name='style')

    op.drop_constraint('state_country_ISO_number_fk', 'state', type_='foreignkey')
    op.drop_constraint('state_id_uindex', 'state', type_='unique')

    op.drop_constraint('country_name_uindex', 'country', type_='unique')
    op.drop_index(op.f('country_ISO3_uindex'), table_name='country')
    op.drop_index(op.f('country_ISO_uindex'), table_name='country')
    op.drop_index(op.f('country_ISO_number_uindex'), table_name='country')

    # ### end Alembic commands ###

