"""kata history & tips

Revision ID: 596e99ecaed4
Revises: dbdb6b58940c
Create Date: 2020-04-24 03:14:25.449264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596e99ecaed4'
down_revision = 'dbdb6b58940c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kata', sa.Column('history', sa.Text(), nullable=True))
    op.add_column('kata', sa.Column('tips', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kata', 'tips')
    op.drop_column('kata', 'history')
    # ### end Alembic commands ###
