"""add_person_ref_cols

Revision ID: 6_add_person_ref_cols
Revises: 5_create_kata_kata_rel
Create Date: 2020-06-15 00:02:33.563474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6_add_person_ref_cols'
down_revision = '5_create_kata_kata_rel'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('persons_hide', sa.Integer(), nullable=True))
    op.add_column('reference', sa.Column('kata_id', sa.Integer(), nullable=True))
    op.alter_column('reference', 'glossary_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'reference', 'kata', ['kata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.alter_column('reference', 'glossary_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('reference', 'kata_id')
    op.drop_column('person', 'persons_hide')
    # ### end Alembic commands ###
