"""org.founder_person_id added

Revision ID: 7803cd1850fc
Revises: 596e99ecaed4
Create Date: 2020-05-04 21:23:20.448604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7803cd1850fc'
down_revision = '596e99ecaed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('founder_person_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org', 'founder_person_id')
    # ### end Alembic commands ###
