"""create pub_rel

Revision ID: 7_create_pub_rel
Revises: 6_add_person_ref_cols
Create Date: 2020-06-15 01:13:04.612928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7_create_pub_rel'
down_revision = '6_add_person_ref_cols'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pub_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.Integer(), nullable=False),
    sa.Column('author_person_id', sa.Integer(), nullable=True),
    sa.Column('subject_person_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),

    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['pub_id'], ['publication.id']),
    sa.ForeignKeyConstraint(['author_person_id'], ['person.id']),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'])
    )

    op.drop_column('publication', 'author_person_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('author_person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('pub_rel')
    # ### end Alembic commands ###
