"""ref_category

Revision ID: 8_ref_category
Revises: 7_create_pub_rel
Create Date: 2020-08-23 21:19:13.124238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8_ref_category'
down_revision = '7_create_pub_rel'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_rel',
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('ref_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ref_category_id'], ['ref_category.id'], ),
    sa.ForeignKeyConstraint(['ref_id'], ['reference.id'], )
    )
    op.drop_column('reference', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('category', mysql.VARCHAR(length=25), nullable=True))
    op.drop_table('ref_rel')
    op.drop_table('ref_category')
    # ### end Alembic commands ###
