"""dojo nullable

Revision ID: 9_dojo_nullable
Revises: 8_ref_category
Create Date: 2020-09-02 23:09:40.620205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9_dojo_nullable'
down_revision = '8_ref_category'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('dojo_email_uindex', table_name='dojo')
    op.drop_index('dojo_fax_uindex', table_name='dojo')
    op.drop_index('dojo_phone_uindex', table_name='dojo')
    op.drop_index('dojo_siteURL_uindex', table_name='dojo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('dojo_siteURL_uindex', 'dojo', ['siteURL'], unique=True)
    op.create_index('dojo_phone_uindex', 'dojo', ['phone'], unique=True)
    op.create_index('dojo_fax_uindex', 'dojo', ['fax'], unique=True)
    op.create_index('dojo_email_uindex', 'dojo', ['email'], unique=True)
    # ### end Alembic commands ###
