"""add language to posts

Revision ID: 40614faf137c
Revises: 69ebe4e548d8
Create Date: 2020-03-03 05:19:45.614455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40614faf137c'
down_revision = '69ebe4e548d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
