"""create kata - add data after

Revision ID: b6a4845f04a2
Revises: ccdade22c9b1
Create Date: 2020-05-27 13:09:42.333212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6a4845f04a2'
down_revision = 'ccdade22c9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(25), nullable=False),
        sa.Column('kanji', sa.String(25), nullable=True),
        sa.Column('creator_person_id', sa.Integer(), nullable=True),
        sa.Column('history', sa.Text(), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_foreign_key('kata_person_creator_fk', 'kata', 'person', ['creator_person_id'], ['id'])

    op.create_table('kata_rel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('kata_id', sa.Integer(), nullable=False),
        sa.Column('style_id', sa.Integer(), nullable=True),
        sa.Column('parent_kata_id', sa.Integer(), nullable=True),
        sa.Column('child_kata_id', sa.Integer(), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.Column('updated_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_foreign_key('kata_id_fk', 'kata_rel', 'kata', ['kata_id'], ['id'])
    op.create_foreign_key('kata_style_id_fk', 'kata_rel', 'style', ['style_id'], ['id'])
    op.create_foreign_key('parent_kata_id_fk', 'kata_rel', 'kata', ['parent_kata_id'], ['id'])
    op.create_foreign_key('child_kata_id_fk', 'kata_rel', 'kata', ['child_kata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('child_kata_id_fk', 'kata_rel', type_='foreignkey')
    op.drop_constraint('parent_kata_id_fk', 'kata_rel', type_='foreignkey')
    op.drop_constraint('kata_style_id_fk', 'kata_rel', type_='foreignkey')
    op.drop_constraint('kata_id_fk', 'kata_rel', type_='foreignkey')
    op.drop_table('kata_rel')

    op.drop_constraint('kata_person_creator_fk', 'kata', type_='foreignkey')
    op.drop_table('kata')
    # ### end Alembic commands ###
