"""glossary techs relationship

Revision ID: bf703eb1b164
Revises: 5a34b5ba14f5
Create Date: 2020-05-09 21:38:35.380107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf703eb1b164'
down_revision = '5a34b5ba14f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tech', 'glossary', ['glossary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tech', type_='foreignkey')
    # ### end Alembic commands ###
